# It is easier to fit three panes 80 char wide consoles on single 15" screen.
max_width = 80
ideal_width = 72
tab_spaces = 4

# Just to save the byte.
newline_style = "Unix"

# Committed FIXMEs never get fixed.
report_todo = "Always"
report_fixme = "Always"

# We use different comment styles for different purposes.
normalise_comments = false

# No backups needed; that's why we use Git.
write_mode = "Overwrite"

# In some places `try!` still trumps.
use_try_shorthand = false

# Visual indentation of chained calls is easier to follow (for me)
chain_base_indent = "Visual"
chain_indent = "Visual"
chain_overflow_last = false
# XXX: But, alas, it seems rustfmt doesn't handle the closures that are
# embedded in chained expressions that well.  This leaves them alone but you
# need to pay some attention to them yourself.
closure_block_indent_threshold = -1

# To make the function body stand out from the function signature.  And the
# rest of the top-levelish forms should follow in the name of consistency.
fn_brace_style = "AlwaysNextLine"
item_brace_style = "AlwaysNextLine"

# This makes the return type stand out from the function arguments.
fn_return_indent = "WithWhereClause"

# As the import (or #include order) in Rust doesn't matter there is no excuse
# to not keep things lexicographically indexed.  Ever seen an English language
# dictionary with random word ordering?
reorder_imports = true